### ISSUE TITLE
commenti

### ISSUE THREAD

**Issue by marte-git** [LucaMorazzano/XML-Rappresentativo#1]
alert non allert

e poi a parte mi spiegate l'uso di dbs vs dbms ;)

comunque il carrello non viene svuotato dopo l'acquisto ...

**Comment by LucaMorazzano** [comment]
Problema carrello risolto.
Non riusciamo a trovare l'errore relativo all'alert, probabilmente si tratta di un errore di digitazione, pertanto ci scusiamo.
Per quanto riguarda la differenza tra dbs e dbms: 
per dbs si intende una collezione di dati organizzati in tabelle e record.
Mentre per dbms si intende il software che gestisce i vari database. Nel caso dell'esercizio consegnato il dbms è phpmyadmin, mentre il dbs è TelefoniXml.
In attesa di un suo riscontro le auguriamo una buona serata.

**Comment by marte-git** [comment]
ok, l'aggiunta di una immagine per il singolo prodotto sarebbe un buon esercizio.
E poi, nella definizione di un telefono vengono inseriti dei dati che poi non vengono visualizzati (forse avete solo dimenticato di scrivere info.php ... che magari dovrebbe avere un paramtero con l'id (o il nome) del telefono.
Fatelo e poi potete intraprendere la tesina.
